
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/navbar";
import Footer from "@/components/Shared/footer";
import axios from "@/utils/axios";
import CustomCursor from "@/components/Shared/Customcursor";
import { Suspense } from "react";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GoApp",
  description: "Generated by create next app",
  icons:{
    icon:'/logo.png',
  }
};
async function getData1() {
  let data;
  await axios
    .get("/page/home", {
      headers: {
        "Accept-Language": "en", 
      },
    })
    .then((res) => {
      data = res.data;
      
    })
    .catch(console.error);


  return { props: { data } };
}

export default async function RootLayout({ children }) {
  const data1=await getData1()
  metadata.title=data1.props.data.data.title
  metadata.description=data1.props.data.data.seo_description
  metadata.icons.icon=data1.props.data.data.seo_image
  return (

    <html lang="en">
      <body className={inter.className}>

      <div className="bg-[#000]">
        <CustomCursor/>
      <Navbar/>
        {children}
        </div>
        <Footer/>
        </body>
    </html>
  );
}
